// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.Infrastructure
{
    public partial class EmailConfig
    {
        public EmailConfig()
        {
            SystemConfigOptions = new HashSet<SystemConfigOption>();
        }

        public Guid Oid { get; set; }
        public string Host { get; set; }
        public string Port { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SenderName { get; set; }

        public virtual ICollection<SystemConfigOption> SystemConfigOptions { get; set; }
    }
}