// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using PrintManagement.Infrastructure.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace PrintManagement.Infrastructure
{
    public partial class PrintManagementContext : DbContext
    {
        public PrintManagementContext()
        {
        }

        public PrintManagementContext(DbContextOptions<PrintManagementContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BackupConfig> BackupConfigs { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<EmailConfig> EmailConfigs { get; set; }
        public virtual DbSet<FinancialConfig> FinancialConfigs { get; set; }
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<PrinterUsageLog> PrinterUsageLogs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SystemConfigOption> SystemConfigOptions { get; set; }
        public virtual DbSet<SystemInfo> SystemInfos { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserConfig> UserConfigs { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<WatermarkConfig> WatermarkConfigs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.BackupConfigConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DepartmentConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DocumentConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EmailConfigConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.FinancialConfigConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PrinterConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PrinterUsageLogConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RoleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SystemConfigOptionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SystemInfoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UserConfigConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UserGroupConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UserRoleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.WatermarkConfigConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
