// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.Infrastructure
{
    public partial class UserConfig
    {
        public Guid Oid { get; set; }
        public int? DefaultBalance { get; set; }
        public int? DefaultRemainPages { get; set; }
    }
}