// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.Infrastructure
{
    public partial class User
    {
        public User()
        {
            Documents = new HashSet<Document>();
            PrinterUsageLogs = new HashSet<PrinterUsageLog>();
            UserRoles = new HashSet<UserRole>();
        }

        public Guid Oid { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool? IsAdmin { get; set; }
        public bool? IsDisable { get; set; }
        public bool? IsRestricted { get; set; }
        public double? Balance { get; set; }
        public int? RemainPages { get; set; }
        public int? TotalJobs { get; set; }
        public int? TotalPages { get; set; }
        public string ResetBy { get; set; }
        public DateTime? ResetDate { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public Guid? IdUserGroup { get; set; }
        public Guid? IdDepartment { get; set; }

        public virtual Department IdDepartmentNavigation { get; set; }
        public virtual UserGroup IdUserGroupNavigation { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<PrinterUsageLog> PrinterUsageLogs { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}