// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.ApiIntegration
{
    public partial class SystemConfigOptionDTO
    {
        public Guid Oid { get; set; }
        public Guid? IdEmailConfig { get; set; }
        public Guid? IdBackupConfig { get; set; }
    }
}