// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;

namespace PrintManagement.ApiIntegration
{
    public static class DocumentStatic {
        public enum SizeUnits {
            Byte, KB, MB, GB, TB, PB, EB, ZB, YB
        }
        public static long ToSize(this Int64 value, SizeUnits unit) {
            return Convert.ToInt64((value / (double)Math.Pow(1024, (Int64)unit)));
        }

        private static readonly Regex fileNameSpecialCharsPattern = new Regex("[^\\w_. ]+", RegexOptions.Compiled);
        public static string GetUniqueFileName(string filePath) {
            var fileName = Path.GetFileName(filePath).Replace(" ", string.Empty);
            fileName = fileNameSpecialCharsPattern.Replace(fileName, "");
            fileName = $"{DateTime.Now:yyyyMMddHHmmss}_{Guid.NewGuid().ToString().Substring(0, 4)}_{fileName}";
            return fileName;
        }
    }
}