// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.ApiIntegration
{
    public partial class FlatDocumentDTO {
        public string OrderNumber { get; set; }
        public string Name { get; set; }
        public string MimeType { get; set; }
        public string SizeKb { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
    }
}