// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.ApiIntegration {
    public partial class FlatUserDTO {
        public string OrderNumber { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public string UserGroup { get; set; }
        public string Balance { get; set; }
        public string TotalJobs { get; set; }
        public string TotalPages { get; set; }
        public string CreatedDate { get; set; }
    }
}