// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.ApiIntegration
{
    public partial class FlatPrinterDTO {
        public string OrderNumber { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public string TotalJobs { get; set; }
        public string TotalPages { get; set; }
        public string LastUsageDate { get; set; }
    }
}