// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.ApiIntegration
{
    public partial class FinancialConfigDTO
    {
        public Guid Oid { get; set; }
        public string CurrencyCode { get; set; }
        public int? DefaultPrintCost { get; set; }
    }
}