// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.ApiIntegration
{
    public partial class SystemInfoDTO
    {
        public Guid Oid { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Author { get; set; }
        public string Status { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int? TotalUser { get; set; }
        public string TotalMoneyProvided { get; set; }
        public string TotalPrinter { get; set; }
        public long? TotalFilePrinted { get; set; }
        public int? TotalFileUploaded { get; set; }
        public int? TotalFileDownload { get; set; }
    }
}