// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.ApiIntegration
{
    public partial class PrinterUsageLogDTO {
        public Guid Oid { get; set; }
        public DateTime? UsageDate { get; set; }
        public string UsageBy { get; set; }
        public double? UsageCost { get; set; }
        /// <summary>
        /// Máy tạo lệnh in
        /// </summary>
        public string MachineName { get; set; }
        public int? JobId { get; set; }
        /// <summary>
        /// Kích thước job
        /// </summary>
        public int? JobSize { get; set; }
        public string JobStatus { get; set; }
        public int? TotalPages { get; set; }
        public int? Copies { get; set; }
        public string DriverName { get; set; }
        public string PrinterName { get; set; }
        public string PrintProcessorName { get; set; }
        /// <summary>
        /// Người dùng đã gửi công việc
        /// </summary>
        public string UserName { get; set; }
        public bool IsColor { get; set; }
        public string DocumentName { get; set; }
        public int? PagesPrinted { get; set; }
        public string PaperKind { get; set; }
        public int? PaperLength { get; set; }
        public int? PaperWidth { get; set; }
        public bool IsLandscape { get; set; }
        public bool IsDuplex { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsCancelled { get; set; }
        public string Signature { get; set; }
        public Guid? IdPrinter { get; set; }
        public Guid? IdDocument { get; set; }
        public Guid? IdUser { get; set; }
    }
}