// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PrintManagement.Infrastructure;
using System;
using System.Collections.Generic;

namespace PrintManagement.Infrastructure.Configurations
{
    public partial class BackupConfigConfiguration : IEntityTypeConfiguration<BackupConfig>
    {
        public void Configure(EntityTypeBuilder<BackupConfig> entity)
        {
            entity.HasKey(e => e.Oid);

            entity.ToTable("BackupConfig");

            entity.Property(e => e.Oid).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.BackupLocation).HasMaxLength(255);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BackupConfig> entity);
    }
}
