// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PrintManagement.Infrastructure;
using System;
using System.Collections.Generic;

namespace PrintManagement.Infrastructure.Configurations
{
    public partial class PrinterConfiguration : IEntityTypeConfiguration<Printer>
    {
        public void Configure(EntityTypeBuilder<Printer> entity)
        {
            entity.HasKey(e => e.Oid);

            entity.ToTable("Printer");

            entity.Property(e => e.Oid).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.CreatedBy).HasMaxLength(255);

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            entity.Property(e => e.DriverName).HasMaxLength(255);

            entity.Property(e => e.LastUsageDate).HasColumnType("datetime");

            entity.Property(e => e.Location).HasMaxLength(255);

            entity.Property(e => e.ModifiedBy).HasMaxLength(255);

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.Note).HasMaxLength(255);

            entity.Property(e => e.PortName).HasMaxLength(255);

            entity.Property(e => e.ResetBy).HasMaxLength(255);

            entity.Property(e => e.ResetDate).HasColumnType("datetime");

            entity.Property(e => e.ServerName).HasMaxLength(255);

            entity.HasOne(d => d.IdDepartmentNavigation)
                .WithMany(p => p.Printers)
                .HasForeignKey(d => d.IdDepartment)
                .HasConstraintName("FK_Printer_Department");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Printer> entity);
    }
}
