// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PrintManagement.Infrastructure;
using System;
using System.Collections.Generic;

namespace PrintManagement.Infrastructure.Configurations
{
    public partial class SystemInfoConfiguration : IEntityTypeConfiguration<SystemInfo>
    {
        public void Configure(EntityTypeBuilder<SystemInfo> entity)
        {
            entity.HasKey(e => e.Oid);

            entity.ToTable("SystemInfo");

            entity.Property(e => e.Oid).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.Author).HasMaxLength(255);

            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Status).HasMaxLength(255);

            entity.Property(e => e.TotalMoneyProvided)
                .HasMaxLength(10)
                .IsFixedLength();

            entity.Property(e => e.TotalPrinter)
                .HasMaxLength(10)
                .IsFixedLength();

            entity.Property(e => e.Version).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SystemInfo> entity);
    }
}
