// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PrintManagement.Infrastructure;
using System;
using System.Collections.Generic;

namespace PrintManagement.Infrastructure.Configurations
{
    public partial class SystemConfigOptionConfiguration : IEntityTypeConfiguration<SystemConfigOption>
    {
        public void Configure(EntityTypeBuilder<SystemConfigOption> entity)
        {
            entity.HasKey(e => e.Oid);

            entity.ToTable("SystemConfigOption");

            entity.Property(e => e.Oid).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.IdBackupConfigNavigation)
                .WithMany(p => p.SystemConfigOptions)
                .HasForeignKey(d => d.IdBackupConfig)
                .HasConstraintName("FK_SystemConfigOption_BackupConfig");

            entity.HasOne(d => d.IdEmailConfigNavigation)
                .WithMany(p => p.SystemConfigOptions)
                .HasForeignKey(d => d.IdEmailConfig)
                .HasConstraintName("FK_SystemConfigOption_EmailConfig");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SystemConfigOption> entity);
    }
}
