// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PrintManagement.Infrastructure;
using System;
using System.Collections.Generic;

namespace PrintManagement.Infrastructure.Configurations
{
    public partial class WatermarkConfigConfiguration : IEntityTypeConfiguration<WatermarkConfig>
    {
        public void Configure(EntityTypeBuilder<WatermarkConfig> entity)
        {
            entity.HasKey(e => e.Oid);

            entity.ToTable("WatermarkConfig");

            entity.Property(e => e.Oid).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.FontFamily).HasMaxLength(255);

            entity.Property(e => e.Name).HasMaxLength(255);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WatermarkConfig> entity);
    }
}
