// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.Infrastructure
{
    public partial class BackupConfigDTO
    {
        public Guid Oid { get; set; }
        public string BackupLocation { get; set; }
        public int? BackupSchedule { get; set; }
        public int? DeleteLogSchedule { get; set; }

    }
}