// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.Infrastructure {
    public partial class WatermarkConfigDTO {
        public Guid Oid { get; set; }
        public string FileImage { get; set; }
        public string Text { get; set; }
        public string FontFamily { get; set; }
        public int? FontSize { get; set; }
        public double? X { get; set; }
        public double? Y { get; set; }
        public int? VerticalAlignment { get; set; }
        public int? HorizontalAlignment { get; set; }
        public double? Height { get; set; }
        public double? Width { get; set; }
        public double? RotateAngle { get; set; }
        public bool? IsBackground { get; set; }
        public double? Opacity { get; set; }
        public int? Classify { get; set; }
        public string Name { get; set; }
    }
}