// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrintManagement.ApiIntegration
{
    public partial class UserRoleDTO
    {
        public Guid Oid { get; set; }
        public Guid? IdUser { get; set; }
        public Guid? IdRole { get; set; }
        public string Status { get; set; }
    }
}